# DDT-Application - Funding Configuration
# Configurazione per supporto finanziario del progetto

# GitHub Sponsors
github: PatrikBaldon

# Altri metodi di supporto
custom:
  - type: "Email"
    url: "mailto:patrik.baldon@aziendaagricola.com"
    description: "Contatta per supporto personalizzato"
  - type: "Website"
    url: "https://github.com/PatrikBaldon/DDT-Application"
    description: "Visita il repository GitHub"

# Messaggio di ringraziamento
message: "Grazie per il supporto a DDT-Application! Il tuo contributo aiuta a mantenere e migliorare l'applicazione per la gestione dei Documenti di Trasporto."