# DDT-Application - Repository Settings
# Configurazione per le impostazioni del repository

# Informazioni generali
name: "DDT-Application"
description: "Sistema di gestione Documenti di Trasporto per aziende agricole - Applicazione Electron cross-platform"
topics:
  - "electron"
  - "django"
  - "ddt"
  - "agricoltura"
  - "gestione-documenti"
  - "trasporto"
  - "desktop-app"
  - "cross-platform"

# Impostazioni repository
has_issues: true
has_projects: true
has_wiki: true
has_discussions: true
allow_squash_merge: true
allow_merge_commit: true
allow_rebase_merge: true
allow_auto_merge: true
delete_branch_on_merge: true

# Protezione branch main
branch_protection:
  required_status_checks:
    strict: true
    contexts:
      - "build-windows"
      - "build-macos"
      - "build-linux"
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  restrictions:
    users: []
    teams: []

# Impostazioni sicurezza
vulnerability_alerts: true
secret_scanning: true
secret_scanning_push_protection: true

# Impostazioni notifiche
notifications:
  security_updates: true
  dependency_updates: true
  discussions: true
  issues: true
  pull_requests: true

# Impostazioni community
community_health:
  issue_templates: true
  pull_request_templates: true
  contributing_guidelines: true
  code_of_conduct: true
  license: true
  readme: true