# Generated by Django 5.2.3 on 2025-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatoNumerazioneDDT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("aaaa-num", "AAAA-NUM (es: 2024-0001)"),
                            ("num", "NUM (es: 0001)"),
                            ("mmaa-num", "MMAA-NUM (es: 1224-0001)"),
                            ("aa-num", "AA-NUM (es: 24-0001)"),
                            ("custom", "Personalizzato"),
                        ],
                        default="aaaa-num",
                        max_length=20,
                        verbose_name="Formato Numerazione",
                    ),
                ),
                (
                    "formato_personalizzato",
                    models.CharField(
                        blank=True,
                        help_text="Usa {anno} per l'anno, {mese} per il mese, {numero} per il numero progressivo",
                        max_length=100,
                        verbose_name="Formato Personalizzato",
                    ),
                ),
                (
                    "numero_iniziale",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Numero Iniziale"
                    ),
                ),
                (
                    "lunghezza_numero",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Numero di cifre per il numero progressivo (es: 4 = 0001, 3 = 001)",
                        verbose_name="Lunghezza Numero",
                    ),
                ),
                ("attivo", models.BooleanField(default=True, verbose_name="Attivo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Formato Numerazione DDT",
                "verbose_name_plural": "Formati Numerazione DDT",
            },
        ),
        migrations.AddField(
            model_name="ddt",
            name="note_centrali",
            field=models.TextField(
                blank=True,
                help_text="Note da inserire al centro delle righe della tabella prodotti",
                verbose_name="Note Centrali",
            ),
        ),
        migrations.AddField(
            model_name="destinazione",
            name="codice_stalla",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Codice Stalla"
            ),
        ),
        migrations.AddField(
            model_name="vettore",
            name="licenza_trasporto_animali",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Licenza Trasporto Animali Vivi",
            ),
        ),
    ]
