# Generated by Django 5.2.3 on 2025-09-15 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0002_formatonumerazioneddt_ddt_note_centrali_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mittente",
            name="cap",
        ),
        migrations.RemoveField(
            model_name="mittente",
            name="citta",
        ),
        migrations.RemoveField(
            model_name="mittente",
            name="indirizzo",
        ),
        migrations.RemoveField(
            model_name="mittente",
            name="provincia",
        ),
        migrations.RemoveField(
            model_name="mittente",
            name="sede_legale",
        ),
        migrations.RemoveField(
            model_name="vettore",
            name="licenza_trasporto_animali",
        ),
        migrations.RemoveField(
            model_name="vettore",
            name="targa",
        ),
        migrations.AddField(
            model_name="vettore",
            name="licenza_bdn",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Licenza BDN per Trasporto Animali Vivi",
            ),
        ),
        migrations.CreateModel(
            name="SedeMittente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome Sede")),
                (
                    "indirizzo",
                    models.CharField(max_length=300, verbose_name="Indirizzo"),
                ),
                (
                    "cap",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{5}$", "CAP deve essere di 5 cifre"
                            )
                        ],
                        verbose_name="CAP",
                    ),
                ),
                ("citta", models.CharField(max_length=100, verbose_name="Città")),
                (
                    "provincia",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$",
                                "Provincia deve essere di 2 lettere maiuscole",
                            )
                        ],
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "codice_stalla",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Codice Stalla"
                    ),
                ),
                (
                    "sede_legale",
                    models.BooleanField(default=False, verbose_name="Sede Legale"),
                ),
                ("attiva", models.BooleanField(default=True, verbose_name="Attiva")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mittente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sedi",
                        to="ddt_app.mittente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede Mittente",
                "verbose_name_plural": "Sedi Mittente",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="ddt",
            name="sede_mittente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ddt_app.sedemittente",
                verbose_name="Sede Mittente",
            ),
        ),
        migrations.CreateModel(
            name="TargaVettore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "targa",
                    models.CharField(max_length=10, verbose_name="Targa Veicolo"),
                ),
                (
                    "tipo_veicolo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Tipo Veicolo"
                    ),
                ),
                ("attiva", models.BooleanField(default=True, verbose_name="Attiva")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vettore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targhe",
                        to="ddt_app.vettore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Targa Vettore",
                "verbose_name_plural": "Targhe Vettore",
                "ordering": ["targa"],
            },
        ),
        migrations.AddField(
            model_name="ddt",
            name="targa_vettore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ddt_app.targavettore",
                verbose_name="Targa Veicolo",
            ),
        ),
    ]
