# Generated by Django 5.2.3 on 2025-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0003_remove_mittente_cap_remove_mittente_citta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddt",
            name="trasporto_mezzo",
            field=models.CharField(
                choices=[
                    ("mittente", "Mittente"),
                    ("vettore", "Vettore"),
                    ("destinatario", "Destinatario"),
                ],
                max_length=20,
                verbose_name="Trasporto a Mezzo di",
            ),
        ),
    ]
