# Generated by Django 5.2.3 on 2025-09-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0004_alter_ddt_trasporto_mezzo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CausaleTrasporto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(max_length=10, unique=True, verbose_name="Codice"),
                ),
                (
                    "descrizione",
                    models.CharField(max_length=200, verbose_name="Descrizione"),
                ),
                ("attiva", models.BooleanField(default=True, verbose_name="Attiva")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Causale di Trasporto",
                "verbose_name_plural": "Causali di Trasporto",
                "ordering": ["codice"],
            },
        ),
        migrations.AlterField(
            model_name="ddt",
            name="causale_trasporto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ddt_app.causaletrasporto",
                verbose_name="Causale di Trasporto",
            ),
        ),
    ]
