# Generated by Django 5.2.3 on 2025-09-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0005_causaletrasporto_alter_ddt_causale_trasporto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vettore",
            name="autista",
        ),
        migrations.RemoveField(
            model_name="vettore",
            name="licenza_bdn",
        ),
        migrations.RemoveField(
            model_name="vettore",
            name="patente",
        ),
        migrations.AddField(
            model_name="vettore",
            name="autorizzazione_animali_vivi",
            field=models.BooleanField(
                default=False, verbose_name="Autorizzazione Trasporto Animali Vivi"
            ),
        ),
        migrations.CreateModel(
            name="Autista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("cognome", models.CharField(max_length=50, verbose_name="Cognome")),
                (
                    "patente",
                    models.CharField(max_length=20, verbose_name="Numero Patente"),
                ),
                (
                    "licenza_bdn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Licenza BDN per Trasporto Animali Vivi",
                    ),
                ),
                ("attivo", models.BooleanField(default=True, verbose_name="Attivo")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vettore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autisti",
                        to="ddt_app.vettore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autista",
                "verbose_name_plural": "Autisti",
                "ordering": ["cognome", "nome"],
            },
        ),
    ]
