# Generated by Django 5.2.3 on 2025-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0006_remove_vettore_autista_remove_vettore_licenza_bdn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autista",
            name="licenza_bdn",
        ),
        migrations.AlterField(
            model_name="autista",
            name="patente",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Numero Patente"
            ),
        ),
    ]
