# Generated by Django 5.2.3 on 2025-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0007_remove_autista_licenza_bdn_alter_autista_patente"),
    ]

    operations = [
        migrations.AddField(
            model_name="vettore",
            name="licenza_bdn",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numero Licenza BDN"
            ),
        ),
    ]
