# Generated by Django 5.2.3 on 2025-09-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0008_vettore_licenza_bdn"),
    ]

    operations = [
        migrations.AddField(
            model_name="ddt",
            name="autista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ddt_app.autista",
                verbose_name="Autista",
            ),
        ),
    ]
