# Generated by Django 5.2.3 on 2025-09-19 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0009_ddt_autista"),
    ]

    operations = [
        migrations.AddField(
            model_name="ddt",
            name="targa_vettore_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ddt_targa_2",
                to="ddt_app.targavettore",
                verbose_name="Targa Veicolo 2",
            ),
        ),
        migrations.AlterField(
            model_name="ddt",
            name="targa_vettore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ddt_targa_1",
                to="ddt_app.targavettore",
                verbose_name="Targa Veicolo 1",
            ),
        ),
    ]
