# Generated by Django 5.2.3 on 2025-09-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddt_app", "0010_add_second_targa_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="mittente",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo"
            ),
        ),
    ]
