name: Deploy Download Page

on:
  push:
    branches: [ main ]
    paths: [ 'installer/DOWNLOAD_PAGE.md' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install -g @github-docs/github-docs-cli
        
    - name: Convert Markdown to HTML
      run: |
        # Crea directory per GitHub Pages
        mkdir -p docs
        
        # Converte DOWNLOAD_PAGE.md in HTML
        pandoc installer/DOWNLOAD_PAGE.md -o docs/index.html \
          --standalone \
          --css https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown-light.min.css \
          --metadata title="DDT Manager - Download" \
          --template <(echo '<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{title}}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown-light.min.css">
  <style>
    .markdown-body { max-width: 980px; margin: 0 auto; padding: 45px; }
    .markdown-body h1 { border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }
    .markdown-body h2 { border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }
    .markdown-body h3 { border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }
    .markdown-body blockquote { border-left: 4px solid #dfe2e5; padding-left: 16px; }
    .markdown-body code { background-color: rgba(27,31,35,0.05); padding: 0.2em 0.4em; border-radius: 3px; }
    .markdown-body pre { background-color: #f6f8fa; padding: 16px; border-radius: 6px; }
    .markdown-body pre code { background-color: transparent; padding: 0; }
    .markdown-body table { border-collapse: collapse; border-spacing: 0; }
    .markdown-body table th, .markdown-body table td { border: 1px solid #dfe2e5; padding: 6px 13px; }
    .markdown-body table th { background-color: #f6f8fa; font-weight: 600; }
    .markdown-body table tr:nth-child(2n) { background-color: #f6f8fa; }
  </style>
</head>
<body>
  <div class="markdown-body">
    {{content}}
  </div>
</body>
</html>')
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        cname: ddt-manager.aziendaagricola.com
