name: Release DDT Manager

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: npm install
        
    - name: Setup Django
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput
        
    - name: Build Electron app
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          npm run build-win
        elif [ "$RUNNER_OS" == "macOS" ]; then
          npm run build-mac
        else
          npm run build-linux
        fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ddt-manager-${{ matrix.os }}
        path: dist/

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: ddt-manager-windows-latest
        path: dist/windows/
        
    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: ddt-manager-macos-latest
        path: dist/macos/
        
    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: ddt-manager-ubuntu-latest
        path: dist/linux/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/windows/*
          dist/macos/*
          dist/linux/*
        body: |
          ## DDT Manager v${{ github.ref_name }}
          
          ### 🎉 Prima Release Electron
          
          Questa è la prima release dell'applicazione Electron per la gestione dei Documenti di Trasporto.
          
          ### 📦 Installazione
          
          **Windows:**
          - Scarica `DDT_Manager_Setup_1.0.0.exe`
          - Esegui l'installer come amministratore
          - Segui le istruzioni per installare Python e Node.js se necessario
          
          **macOS:**
          - Scarica `DDT_Manager-1.0.0.dmg`
          - Apri il file DMG
          - Trascina l'applicazione in Applications
          
          **Linux:**
          - Scarica `DDT_Manager-1.0.0.AppImage`
          - Rendi eseguibile: `chmod +x DDT_Manager-1.0.0.AppImage`
          - Esegui: `./DDT_Manager-1.0.0.AppImage`
          
          ### ✨ Caratteristiche
          
          - 🖥️ **Applicazione Desktop**: Interfaccia nativa per Windows, macOS e Linux
          - 📄 **Gestione DDT Completa**: Creazione, modifica e visualizzazione documenti
          - 📊 **Generazione PDF**: PDF professionali con layout ottimizzato
          - 🔄 **Aggiornamenti Automatici**: Controllo e installazione aggiornamenti
          - 💾 **Backup Automatico**: Sistema di backup integrato per i dati
          - 📈 **Monitoraggio Performance**: Tracciamento delle performance dell'applicazione
          - 🔔 **Notifiche Desktop**: Sistema di notifiche per l'utente
          - ⚙️ **Gestione Impostazioni**: Configurazione persistente dell'applicazione
          
          ### 🔧 Prerequisiti
          
          - Python 3.8+ (installato automaticamente dall'installer)
          - Node.js 16+ (installato automaticamente dall'installer)
          - 500MB di spazio su disco
          - Connessione internet per aggiornamenti
          
          ### 🚀 Sviluppato da
          
          **Patrik Baldon** per **Azienda Agricola BB&F**
          
          ### 📞 Supporto
          
          Per supporto tecnico o segnalazione bug, visita:
          - [GitHub Issues](https://github.com/PatrikBaldon/DDT-Application/issues)
          - Email: patrik.baldon@aziendaagricola.com
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
